Feature/scrum 35 pre push (#9)
* chore(SCRUM29): exercise

* chore(SCRUM-35): configure husky pre-push lint validation

* test(SCRUM-33): testing linter

* fix(SCRUM-35): modify gitignore and husky pre-push fyle

* fix(SCRUM-35): modify gitignore and husky pre-push fyle

* docs(SCRUM-17): add ESP32 Wi-Fi and HTTP documentation

* chore(SCRUM-17): revert incorrect branch commit

* fix(SCRUM-35): move lint to pre-commit and tests to pre-push

* fix(SCRUM-35): move lint to pre-commit and tests to pre-push

---------

Co-authored-by: ValentinoZucchellaPaz <vzucchellapaz@gmail.com>
Co-authored-by: Santino Chesta <santinochestamarozzi@gmail.com>

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,5 +1,12 @@
-echo "Running NestJS lint..."
+#!/bin/sh
 
 cd backend/nestjs || exit 1
 
-npm run lint
+echo "Running build validation..."
+
+npm run build
+
+if [ $? -ne 0 ]; then
+  echo "Build failed. Push aborted."
+  exit 1
+fi
